### PR TITLE
Daily xp progress method.

### PR DESCRIPTION
**Pull request by joshcoales**
This needs merging after [the fixing-tests PR](https://github.com/KartikTalwar/Duolingo/pull/70).

As suggested on this issue: https://github.com/KartikTalwar/Duolingo/issues/74

This adds a get_daily_xp_progress() method, which returns a dict like so:
```
{
  "xp_goal": 20,
  "lessons_today": [
    {
      "eventType": "LESSON",
      "xp": 14,
      "skillId": "f7c1817be508d80f480bccf40490099e",
      "time": 1580492492
    },
    {
      "eventType": "LESSON",
      "xp": 12,
      "skillId": "2ce503cd8b2557d75d4d9df2ce9700ef",
      "time": 1580499257
    }
  ],
  "xp_today": 26
}
```

It uses `xpGoal`, `xpGains` and `streakData`.
Unfortunately `xpGains` lists all lessons completed on the last day with any lessons completed? So I'm using `streakData.updatedTimestamp` to get the last local midnight time(?) and then filtering to only include lessons after that.

I debated returning some DailysXpProgress object, with the 3 parameters, but that might be overkill, and a dict with fixed keys seems fine?

### CODE REVIEW

**Comment by KartikTalwar** [comment]
Hey @joshcoales I've made you a collaborator on this repo and you should now be able to merge all PRs and modify master. Let me know what else you need from me to setup any other ancillary service

**Comment by joshcoales** [comment]
The other services that come to mind are the travis project: https://travis-ci.org/KartikTalwar/Duolingo
and the pypi package: https://pypi.org/project/duolingo-api/ 

I'm not too sure how permissions would be given for those things though, or whether you would need to set those up

**Comment by KartikTalwar** [comment]
I think I setup travis so that any repo collaborator should be able to use and play with it. And if you can let me know if your pypi username, I can add you as a collaborator there as well.

I think you should definitely merge smaller or immediate fixes without review but if there are bigger diffs, I'm more than happy to help review them. If you can point me to which PRs are the most important right now, I can also try to prioritize a review for those first on my end

**Comment by joshcoales** [comment]
My username on pypi should be joshcoales now, I hadn't got one before it turns out, whoops.

The biggest PR at the moment is this one: https://github.com/KartikTalwar/Duolingo/pull/70 as it removes a couple methods which can no longer be supported, and stuff

**Comment by KartikTalwar** [comment]
Added to pypi and please feel free to merge #70

**Comment by joshcoales** [comment]
> 
> 
> I think I setup travis so that any repo collaborator should be able to use and play with it. And if you can let me know if your pypi username, I can add you as a collaborator there as well.
> 
> I think you should definitely merge smaller or immediate fixes without review but if there are bigger diffs, I'm more than happy to help review them. If you can point me to which PRs are the most important right now, I can also try to prioritize a review for those first on my end

It looks like you need to set up the travis hook:
https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator

**Pull request merged**
