### PR TITLE
Add a function to search for a word in the dictionary

### PR DESCRIPTION
**Pull request by atmatto**
I added a function which utilizes `https://duolingo-lexicon-prod.duolingo.com/api/1/search` endpoint and lets users search for a word in the Duolingo dictionary. It could be used for example to convert a word to a lexeme ID.

### CODE REVIEW

**Comment by atmatto** [comment]
There might be one problem, this endpoint may use different language abbreviations than other endpoints. For example Dutch has the abbreviation `dn`, but here it is `nl-NL`. Other languages can have the same abbreviations as normally, for example Spanish - `es`. When you use a wrong abbreviation, the API won't notify you about that error, but it will just return an empty list.

**Comment by SpangleLabs** [comment]
This seems useful!
Could you add a simple test in `tests.py`, perhaps? (Even though we do have some tests failing at the moment)

**Comment by atmatto** [comment]
I added a test but I haven't run it because I didn't want to use my personal account for it.
By the way, as far as I know you don't need to be logged in to use this endpoint. I don't know if this can be valuable information.

**Comment by Otto-AA** [comment]
This does not seem to work anymore, for instance https://duolingo-lexicon-prod.duolingo.com/api/1/search?exactness=1&languageId=en&query=solos&uiLanguageId=es redirects to duolingo.com

**Comment by atmatto** [comment]
That's true, Duolingo has disabled the dictionary some time ago. If you really want to use it in spite of this, then you can check out that: https://github.com/atmatto/dictrec

**Pull request closed without merging**
